# Generated by Django 2.1.2 on 2018-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marca_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default='Rua A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='Fulano', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
