# Generated by Django 2.1.2 on 2018-11-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181128_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='nome',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
