# Generated by Django 2.1.2 on 2018-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
