# Generated by Django 2.1.2 on 2018-11-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mensalista'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
